# Generated by Django 5.2.14 on 2026-05-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
