# Generated by Django 5.2.14 on 2026-05-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_produto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
